# kubernetes/helmfile.d/backend.yaml
releases:
  - name: hallucination-backend
    namespace: hallucination-prod
    chart: ../charts/hallucination-backend
    installed: {{ .Environment.Values.backend.enabled }}
    values:
      - ../values/backend-prod.yaml