# kubernetes/charts/hallucination-backend/templates/secret.yaml
{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MLFLOW_TRACKING_URI: {{ .Values.secrets.mlflowTrackingUri | quote }}
  MLFLOW_S3_ENDPOINT_URL: {{ .Values.secrets.mlflowS3EndpointUrl | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}

{{- if .Values.secrets.hfToken }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hf-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.secrets.hfToken | quote }}
{{- end }}
{{- end }}