# kubernetes/charts/hallucination-backend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hallucination-backend
spec:
  selector:
    app: hallucination-backend
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000