apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://monitoring-stack-prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id\":\"(\\w+)"
          name: TraceID
          url: '$${__value.raw}'
  - name: Jaeger
    type: jaeger
    url: http://jaeger-query:16686
    uid: jaeger