{{- if .Values.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-aws-secret
type: Opaque
stringData:
  accessKeyId: {{ .Values.aws.accessKeyId | quote }}
  secretAccessKey: {{ .Values.aws.secretAccessKey | quote }}
{{- end }}