# observability/prometheus/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hallucination-backend-monitor
  namespace: hallucination-prod
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: hallucination-chart-backend
  namespaceSelector:
    matchNames:
      - hallucination-prod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: evidently-drift-monitor
  namespace: hallucination-prod
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: evidently-drift-service
  namespaceSelector:
    matchNames:
      - hallucination-prod
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s