FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DISABLE_MODEL=true
ENV PYTHONPATH=/app

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-ci.txt .
COPY requirements-test.txt .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
        -r requirements-ci.txt \
        -r requirements-test.txt

COPY backend backend
COPY tests tests

CMD ["pytest", "--cov=backend", "--cov-report=term-missing"]