# kubernetes/helmfile.yaml
environments:
  prod:
    values:
      - values/platform-prod.yaml
      - values/backend-prod.yaml
      - values/model-prod.yaml

helmDefaults:
  wait: true
  timeout: 600
  atomic: true

releases:
  - name: mlflow
    namespace: hallucination-prod
    chart: charts/mlflow

  - name: mlflow-runtime
    namespace: hallucination-prod
    chart: charts/mlflow-runtime

  - name: hallucination-backend
    namespace: hallucination-prod
    chart: charts/hallucination-backend

  - name: hallucination-model
    namespace: hallucination-prod
    chart: charts/hallucination-model
