# yaml-language-server: $schema=https://raw.githubusercontent.com/community-charts/mlflow/main/charts/mlflow/values.schema.json
# iac/ansible/values-mlflow.yaml
mlflow:
  image:
    repository: ghcr.io/kserve/mlflowserver
    tag: "0.11.2"

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"