# kubernetes/charts/hallucination-model/templates/inferenceservice.yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.model.name }}
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      storageUri: {{ .Values.mlflow.storageUri | quote }}